<?php

add_action('init', function () {
    $labels = [
        'name'                     => __('Movies', 'bb-movie'),
        'singular_name'            => __('Movie', 'bb-movie'),
        'menu_name'                => __('Movies', 'bb-movie'),
        'all_items'                => __('All Movies', 'bb-movie'),
        'add_new'                  => __('Add new', 'bb-movie'),
        'add_new_item'             => __('Add new Movie', 'bb-movie'),
        'edit_item'                => __('Edit Movie', 'bb-movie'),
        'new_item'                 => __('New Movie', 'bb-movie'),
        'view_item'                => __('View Movie', 'bb-movie'),
        'view_items'               => __('View Movies', 'bb-movie'),
        'search_items'             => __('Search Movies', 'bb-movie'),
        'not_found'                => __('No Movies found', 'bb-movie'),
        'not_found_in_trash'       => __('No Movies found in trash', 'bb-movie'),
        'parent'                   => __('Parent Movie:', 'bb-movie'),
        'featured_image'           => __('Featured image for this Movie', 'bb-movie'),
        'set_featured_image'       => __('Set featured image for this Movie', 'bb-movie'),
        'remove_featured_image'    => __('Remove featured image for this Movie', 'bb-movie'),
        'use_featured_image'       => __('Use as featured image for this Movie', 'bb-movie'),
        'archives'                 => __('Movie archives', 'bb-movie'),
        'insert_into_item'         => __('Insert into Movie', 'bb-movie'),
        'uploaded_to_this_item'    => __('Upload to this Movie', 'bb-movie'),
        'filter_items_list'        => __('Filter Movies list', 'bb-movie'),
        'items_list_navigation'    => __('Movies list navigation', 'bb-movie'),
        'items_list'               => __('Movies list', 'bb-movie'),
        'attributes'               => __('Movies attributes', 'bb-movie'),
        'name_admin_bar'           => __('Movie', 'bb-movie'),
        'item_published'           => __('Movie published', 'bb-movie'),
        'item_published_privately' => __('Movie published privately.', 'bb-movie'),
        'item_reverted_to_draft'   => __('Movie reverted to draft.', 'bb-movie'),
        'item_scheduled'           => __('Movie scheduled', 'bb-movie'),
        'item_updated'             => __('Movie updated.', 'bb-movie'),
        'parent_item_colon'        => __('Parent Movie:', 'bb-movie'),
    ];

    $args = [
        'label'                 => __('Movies', 'bb-movie'),
        'labels'                => $labels,
        'description'           => '',
        'public'                => true,
        'publicly_queryable'    => true,
        'show_ui'               => true,
        'show_in_rest'          => true,
        'rest_base'             => 'movies',
        'rest_controller_class' => 'WP_REST_Posts_Controller',
        'has_archive'           => true,
        'show_in_menu'          => true,
        'show_in_nav_menus'     => true,
        'delete_with_user'      => false,
        'exclude_from_search'   => false,
        'capability_type'       => 'post',
        'map_meta_cap'          => true,
        'hierarchical'          => false,
        'rewrite'               => ['slug' => 'movies', 'with_front' => true],
        'query_var'             => true,
        'menu_icon'             => 'dashicons-video-alt2',
        'supports'              => ['title', 'editor', 'thumbnail', 'custom-fields'],
        'show_in_graphql'       => true,
        'graphql_single_name'   => __('Movie', 'bb-movie'),
        'graphql_plural_name'   => __('Movies', 'bb-movie'),
    ];

    register_post_type('movie', $args);
});

add_action('init', function () {
    $labels = [
        'name'                       => __('Genres', 'bb-movie'),
        'singular_name'              => __('Genre', 'bb-movie'),
        'menu_name'                  => __('Genres', 'bb-movie'),
        'all_items'                  => __('All Genres', 'bb-movie'),
        'edit_item'                  => __('Edit Genre', 'bb-movie'),
        'view_item'                  => __('View Genre', 'bb-movie'),
        'update_item'                => __('Update Genre name', 'bb-movie'),
        'add_new_item'               => __('Add new Genre', 'bb-movie'),
        'new_item_name'              => __('New Genre name', 'bb-movie'),
        'parent_item'                => __('Parent Genre', 'bb-movie'),
        'parent_item_colon'          => __('Parent Genre:', 'bb-movie'),
        'search_items'               => __('Search Genres', 'bb-movie'),
        'popular_items'              => __('Popular Genres', 'bb-movie'),
        'separate_items_with_commas' => __('Separate Genres with commas', 'bb-movie'),
        'add_or_remove_items'        => __('Add or remove Genres', 'bb-movie'),
        'choose_from_most_used'      => __('Choose from the most used Genres', 'bb-movie'),
        'not_found'                  => __('No Genres found', 'bb-movie'),
        'no_terms'                   => __('No Genres', 'bb-movie'),
        'items_list_navigation'      => __('Genres list navigation', 'bb-movie'),
        'items_list'                 => __('Genres list', 'bb-movie'),
    ];

    $args = [
        'label'                 => __('Genres', 'bb-movie'),
        'labels'                => $labels,
        'public'                => true,
        'publicly_queryable'    => true,
        'hierarchical'          => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'show_in_nav_menus'     => true,
        'query_var'             => true,
        'rewrite'               => ['slug' => 'genres', 'with_front' => true],
        'show_admin_column'     => true,
        'show_in_rest'          => true,
        'rest_base'             => 'genres',
        'rest_controller_class' => 'WP_REST_Terms_Controller',
        'show_in_quick_edit'    => false,
        'show_in_graphql'       => true,
        'graphql_single_name'   => __('Genre', 'bb-movie'),
        'graphql_plural_name'   => __('Genres', 'bb-movie'),
    ];

    register_taxonomy('genre', ['movie'], $args);
});
